// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToBuy.Data;

namespace ToBuy.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ToBuy.Models.Iten", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.Property<int>("Codigopedido")
                        .HasColumnType("int")
                        .HasColumnName("CODIGOPEDIDO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("Valoritem")
                        .HasColumnType("numeric(13,2)")
                        .HasColumnName("VALORITEM");

                    b.HasKey("Codigo");

                    b.HasIndex("Codigopedido");

                    b.ToTable("ITENS");
                });

            modelBuilder.Entity("ToBuy.Models.Pedido", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime>("Datapedido")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAPEDIDO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("STATUS")
                        .IsFixedLength(true);

                    b.Property<decimal>("Valorpedido")
                        .HasColumnType("numeric(13,2)")
                        .HasColumnName("VALORPEDIDO");

                    b.HasKey("Codigo");

                    b.ToTable("PEDIDOS");
                });

            modelBuilder.Entity("ToBuy.Models.Iten", b =>
                {
                    b.HasOne("ToBuy.Models.Pedido", "CodigopedidoNavigation")
                        .WithMany("Itens")
                        .HasForeignKey("Codigopedido")
                        .HasConstraintName("FK_ITENS_PEDIDOS")
                        .IsRequired();

                    b.Navigation("CodigopedidoNavigation");
                });

            modelBuilder.Entity("ToBuy.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
